swagger: "2.0"
info:
  description: "Config API"
  version: "1.0.0"
  title: "Config Value"
  contact:
    email: "shoothzj@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/v1"
schemes:
  - "https"
  - "http"
parameters:
  env:
    in: "path"
    name: "env"
    required: true
    type: string
    pattern: "[a-fA-F]{1,31}"
  cluster:
    in: "path"
    name: "cluster"
    required: true
    type: string
    pattern: "[a-fA-F]{1,31}"
  config_name:
    in: "path"
    name: "config_name"
    required: true
    type: string
    pattern: "[a-fA-F]{1,31}"
  key:
    in: "path"
    name: "key"
    required: true
    type: string
    pattern: "[a-fA-F]{1,31}"
paths:
  /envs/{env}/clusters/{cluster}/configs/{config_name}/keys:
    post:
      tags:
        - "config value"
      summary: "create a config value"
      description: ""
      operationId: "createConfigValue"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - $ref: "#/parameters/env"
        - $ref: "#/parameters/cluster"
        - $ref: "#/parameters/config_name"
        - in: "body"
          name: "body"
          description: "Config Body"
          required: true
          schema:
            $ref: "#/definitions/CreateConfigValueReq"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/CreateConfigValueResp"
        "405":
          description: "Invalid input"
    get:
      tags:
        - "config value"
      summary: "batch get according to key list"
      description: ""
      operationId: "getConfigs"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - $ref: "#/parameters/env"
        - $ref: "#/parameters/cluster"
        - $ref: "#/parameters/config_name"
        - in: "body"
          name: "body"
          description: "get config value body"
          required: true
          schema:
            $ref: "#/definitions/GetConfigValueListReq"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/GetConfigValueListResp"
        "405":
          description: "Invalid input"
  /envs/{env}/clusters/{cluster}/configs/{config_name}/sync:
    post:
      tags:
        - "config value"
      summary: "sync config value"
      description: ""
      operationId: "syncConfigValue"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - $ref: "#/parameters/env"
        - $ref: "#/parameters/cluster"
        - $ref: "#/parameters/config_name"
        - in: "body"
          name: "body"
          description: "Sync Config Body"
          required: true
          schema:
            $ref: "#/definitions/SyncConfigValueReq"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/SyncConfigValueResp"
        "405":
          description: "Invalid input"
  /envs/{env}/clusters/{cluster}/configs/{config_name}/keys/{key}:
    put:
      tags:
        - "config value"
      summary: "update config value"
      description: ""
      operationId: "updateConfigValue"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - $ref: "#/parameters/env"
        - $ref: "#/parameters/cluster"
        - $ref: '#/parameters/config_name'
        - $ref: '#/parameters/key'
        - in: "body"
          name: "body"
          description: "Update Config Body"
          required: true
          schema:
            $ref: "#/definitions/UpdateConfigValueReq"
      responses:
        "405":
          description: "Invalid input"
    get:
      tags:
        - "config value"
      summary: "get config value"
      description: ""
      operationId: "getConfigValue"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - $ref: "#/parameters/env"
        - $ref: "#/parameters/cluster"
        - $ref: '#/parameters/config_name'
        - $ref: '#/parameters/key'
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/GetConfigValueResp"
        "405":
          description: "Invalid input"
    delete:
      tags:
        - "config value"
      summary: "delete config"
      description: ""
      operationId: "delete_config"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - $ref: "#/parameters/env"
        - $ref: "#/parameters/cluster"
        - $ref: '#/parameters/config_name'
        - $ref: '#/parameters/key'
      responses:
        "204":
          description: "No Content"
        "405":
          description: "Invalid input"
definitions:
  CreateConfigValueReq:
    type: "object"
    properties:
      key:
        type: "string"
        description: "key name"
      content:
        type: "string"
        description: "value content"
  GetConfigValueListReq:
    type: "object"
    properties:
      key_list:
        type: "array"
        items:
          type: "string"
  UpdateConfigValueReq:
    type: "object"
    properties:
      version:
        type: "integer"
        format: "int8"
        description: "old data's version"
      content:
        type: "string"
        description: "value content"
  SyncConfigValueReq:
    type: "object"
    properties:
      sync_items:
        type: "array"
        description: "sync items"
        items:
          $ref: "#/definitions/SyncItem"
  SyncConfigValueResp:
    type: "object"
    properties:
      add_list:
        type: "array"
        description: "sync items"
        items:
          $ref: "#/definitions/SyncItem"
      mod_list:
        type: "array"
        description: "sync items"
        items:
          $ref: "#/definitions/SyncItem"
      del_list:
        type: "array"
        description: "sync items"
        items:
          $ref: "#/definitions/SyncItem"
  CreateConfigValueResp:
    type: "object"
    properties:
      version:
        type: "integer"
        format: "int8"
  GetConfigValueListResp:
    type: "object"
    properties:
      key_list:
        type: "array"
        items:
          $ref: "#/definitions/GetConfigValueResp"
  GetConfigValueResp:
    type: "object"
    properties:
      version:
        type: "integer"
        format: "int8"
      content:
        type: "string"
        description: "config name"
  SyncItem:
    type: "object"
    properties:
      key:
        type: "string"
      version:
        type: "integer"
        format: "int8"